app/views/boards.py
from subprocess import check_output
from subprocess import check_output

from flask import (
    Blueprint,
    redirect,
    render_template,
    request,
    url_for
)

from flask_login import current_user

from ..forms import NewPostForm, NewReplyForm
from ..extensions import db
from ..models import Board, Post, Reply

boards = Blueprint("boards", __name__)

@boards.route("/<boardname>/", methods=["GET", "POST"])
def board(boardname):
    board = Board.query.filter_by(name=boardname).first()
    
    if request.method == "GET":
        board.hits+=1
        db.session.commit()
        
    form = NewPostForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            return abort(403)
        p = Post(content=form.content.data, user=current_user,
                 board=board)
        board.posts.append(p)
        db.session.commit()
        return redirect(url_for("boards.board", boardname=board.name))

    boards = list(sorted(Board.query.all(),
                         key=lambda x: x.hits, reverse=True))[:5]
    sizeofmedia = check_output(["du", "-h", "app/static/media/users"]).decode(
        ).split("\t")[0]
    sizeoftext = check_output(["du", "-h", "app/neochina.sqlite3"]).decode(
        ).split("\t")[0]

    return render_template("board.html", boards=boards, board=board, form=form,
                           posts=reversed(board.posts),
                           sizeofmedia=sizeofmedia.lower(),
                           sizeoftext=sizeoftext.lower(),
                           nousers=len(Board.query.all()),
                           noposts=len(Post.query.all()))

@boards.route("/<boardname>/post/<postid>", methods=["GET", "POST"])
def post(boardname, postid):
    board = Board.query.filter_by(name=boardname).first()
    post = Post.query.filter_by(id=postid).first()
    if not post or post.board != board:
        print('error retrieving post', post.board, board,
              post.board==board)
        return abort(404)
    
    if request.method == "GET":
        post.hits+=1
        db.session.commit()
        
    form = NewReplyForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            return abort(403)
        r = Reply(content=form.content.data, user=current_user,
                  post=post)
        post.replies.append(r)
        db.session.commit()
        return redirect(url_for("boards.post", boardname=board.name,
                                postid=post.id))

    boards = list(sorted(Board.query.all(),
                         key=lambda x: x.hits, reverse=True))[:5]
    sizeofmedia = check_output(["du", "-h", "app/static/media/users"]).decode(
        ).split("\t")[0]
    sizeoftext = check_output(["du", "-h", "app/neochina.sqlite3"]).decode(
        ).split("\t")[0]
    return render_template("post.html", boards=boards, post=post, form=form,
                           replies=post.replies,
                           sizeofmedia=sizeofmedia.lower(),
                           sizeoftext=sizeoftext.lower(),
                           nousers=len(Board.query.all()),
                           noposts=len(Post.query.all()))

app/views/users.py
from os import getcwd
from os.path import join, splitext
from random import SystemRandom
from subprocess import check_output

from flask import (
    abort,
    Blueprint,
    redirect,
    render_template,
    request,
    url_for
)

from flask_login import (
    current_user,
    login_user,
    logout_user
)

from werkzeug.utils import secure_filename
from werkzeug.urls import url_parse

from ..forms import LoginForm, RegisterForm, EditProfileForm
from ..models import User, Board, Post
from ..extensions import db
from ..settings import UPLOAD_FOLDER

users = Blueprint("users", __name__)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            print("No such user or incorrect password")
            return redirect(url_for('users.login'))
        login_user(user)

        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for("main.index")
        return redirect(next_page)

    boards = list(sorted(Board.query.all(),
                         key=lambda x: x.hits, reverse=True))[:5]
    sizeofmedia = check_output(["du", "-h", "app/static/media/users"]).decode(
        ).split("\t")[0]
    sizeoftext = check_output(["du", "-h", "app/neochina.sqlite3"]).decode(
        ).split("\t")[0]
    return render_template("login.html", form=form, boards=boards,
                           sizeofmedia=sizeofmedia,
                           sizeoftext=sizeoftext,
                           nousers=len(Board.query.all()),
                           noposts=len(Post.query.all()))

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("users.login"))

    boards = list(sorted(Board.query.all(),
                         key=lambda x: x.hits, reverse=True))[:5]
    sizeofmedia = check_output(["du", "-h", "app/static/media/users"]).decode(
        ).split("\t")[0]
    sizeoftext = check_output(["du", "-h", "app/neochina.sqlite3"]).decode(
        ).split("\t")[0]
    return render_template("register.html", form=form, boards=boards,
                           sizeofmedia=sizeofmedia.lower(),
                           sizeoftext=sizeoftext.lower(),
                           nousers=len(Board.query.all()),
                           noposts=len(Post.query.all()))

@users.route("/<username>", methods=["GET", "POST"])
def profile(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        return abort(404, f"No such user '{username}' exists!")
    
    form = EditProfileForm()
    if form.validate_on_submit() and user == current_user:
        if form.bio.data:
            user.bio = form.bio.data
            db.session.commit()
            
        if form.avatar.data:
            randomness = SystemRandom().randint(9999,99999)
            filename = secure_filename(
                user.username + str(randomness) + \
                splitext(form.avatar.data.filename)[1])
            request.files[form.avatar.name].save(join(
                getcwd(), "app", UPLOAD_FOLDER, "users",
                filename))
            user.avatar = filename
            db.session.commit()
            
        return redirect(url_for("users.profile",
                                username=user.username))

    boards = list(sorted(Board.query.all(),
                         key=lambda x: x.hits, reverse=True))[:5]
    sizeofmedia = check_output(["du", "-h", "app/static/media/users"]).decode(
        ).split("\t")[0]
    sizeoftext = check_output(["du", "-h", "app/neochina.sqlite3"]).decode(
        ).split("\t")[0]
    return render_template("profile.html", user=user, form=form, boards=boards,
                           sizeofmedia=sizeofmedia.lower(),
                           sizeoftext=sizeoftext.lower(),
                           nousers=len(Board.query.all()),
                           noposts=len(Post.query.all()))

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Neochina</title>
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="nav">
      <ul>
	<span>Most Popular Boards &gt;</span>
	{% for board in boards %}
	<li><a href="{{ url_for('boards.board', boardname=board.name) }}">/{{ board.name }}/</a></li>
	{% endfor %}
      </ul>
    </div>
    
    <main>
      <div class="header">
	<a class="nostyle" href="/"><h1>Neochina</h1></a>
	<p class="quote"><i>Nothing human makes it out of the near future.</i></p>
      </div>

      <div class="authbtns">
	{% if not current_user.is_authenticated %}
	<form class="btn" action="{{ url_for('users.login') }}"><button>Log In</button></form><br>
	<form class="btn" action="{{ url_for('users.register') }}"><button>Register</button></form>
	{% else %}
	<form class="btn" action="{{ url_for('users.profile', username=current_user.username) }}"><button>Profile</button></form><br>
	<form class="btn" action="{{ url_for('users.logout') }}"><button>Log Out</button></form><br>
	{% endif %}
      </div>

      <div class="clear"></div>

      {% block body %}
      {% endblock %}

      <div class="clear"></div><br><br>
      
      <footer>
	<p>{{ nousers }} registered users * {{ noposts }} total posts</p>
	<p>hosting {{ sizeoftext }} of text * {{ sizeofmedia }} of images</p>
	
	<p class="copy"><code>absolutely no copyright (c) MMXX<br>feel free to steal any/all code, images etc</code></p>

	<img alt="The Happy Prince" src="{{ url_for('static', filename='media/thp.jpg') }}"/>

	<p>- thp</p>
      </footer>
      
      </main>
  </body>
</html>

app/templates/board.html
{% extends 'base.html' %}

{% block body %}
<h2>Browsing /{{ board.name }}/</h2>

{% if current_user.is_authenticated %}
<form action="{{ url_for('boards.board', boardname=board.name) }}" method="POST">
  {{ form.hidden_tag() }}

  {% for message in form.content.errors %}
    {{ message }}
  {% endfor %}
  {{ form.content.label }}:<br>
  {{ form.content }}<br>

  {{ form.submit }}
</form>
{% else %}
Please log in to post on this board...
{% endif %}

<h3>Posts</h3>
<ul class="posts">
  {% for post in posts %}
  <li class="post">
    <a class="nostyle" href="{{ url_for('boards.post', boardname=post.board.name, postid=post.id) }}">
      <p class="msg">{{ post.content }}</p></a>
    
    <p class="author">
      <a href="{{ url_for('users.profile', username=post.user.username) }}" class="nounder">
	<img class="av-sm" alt="user profile picture" src="{{ url_for('static', filename='media/users/'+post.user.avatar) }}"/>
      </a>
      <a class="name" href="{{ url_for('users.profile', username=post.user.username) }}">{{ post.user.username }}</a>
      {{ post.date }}
    </p>
  </li>
{% endfor %}
</ul>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block body %}
      <p>Welcome to <span class="nc">Neochina</span> a traditional and functionally minimal web forum. Register above, no email required, and browse the above boards. THP (<span class="nc">NC</span> staff in other words) asks that you adhere to <a href="https://4chan.org/rules">4gag rules</a> until we formulate our own. Such meta discussion will usually take place in <a href="/board/proposals">/proposals/</a> feel free to join in.</p>
      
      <h2>Hot Posts Across All Boards</h2>
      <ul class="posts">
	{% for post in topposts %}
	<li class="post">
	  <a class="nostyle" href="{{ url_for('boards.post', boardname=post.board.name, postid=post.id) }}">
	    <p class="msg">{{ post.content }}</p></a>
    
	  <p class="author">
	    <a href="{{ url_for('users.profile', username=post.user.username) }}" class="nounder">
	      <img class="av-sm" alt="user profile picture" src="{{ url_for('static', filename='media/users/'+post.user.avatar) }}"/>
	    </a>
	    <a class="name" href="{{ url_for('users.profile', username=post.user.username) }}">{{ post.user.username }}</a>
	    {{ post.date }} in
	    <a href="{{ url_for('boards.board', boardname=post.board.name) }}">/{{ post.board.name }}/</a>
	  </p>
	</li>
	{% endfor %}
      </ul>

      <h2>Useful Links</h2>
      <div class="hotlinks">
	<img alt="Eyeball" src="{{ url_for('static', filename='media/homeimage.png') }}" class="secimg"/>
	<ul>
	  <li><a href="{{ url_for('main.index') }}">Home - You are here</a></li>
	  <li><a href="{{ url_for('boards.board', boardname='lounge') }}">Lounge - General chat</a></li>
	  <li><a href="{{ url_for('boards.board', boardname='proposals') }}">Proposals Board - Meta discussion</a></li>
	  <li><a href="https://s3.amazonaws.com/arena-attachments/406213/42bdb859549f609953a0ca61aca0bee3.pdf">Useful book - Fanged Noumena</a></li>
	  <li><a href="https://www.marxists.org/admin/books/manifesto/Manifesto.pdf">Important pamphlet - Communist Manifesto</a></li>
	  <li><a href="http://triggs.djvu.org/djvu-editions.com/BIBLES/KJV/Download.pdf">Also good book - 1611 KJV</a></li>	
	</ul>
	<code>i do not own image shown left</code>
      </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block body %}
<p>Log in below:</p>

<form action="{{ url_for('users.login') }}" method="POST">
  {{ form.hidden_tag() }}

  {% for message in form.username.errors %}
  {{ message }}
  {% endfor %}
  {{ form.username.label }}:<br>
  {{ form.username }}<br>

  {% for message in form.password.errors %}
  {{ message }}
  {% endfor %}
  {{ form.password.label }}:<br>
  {{ form.password }}<br><br>

  {{ form.submit }}
</form>

<p>Alternatively, <a href="{{ url_for('users.register') }}">register</a> here.</p>
{% endblock %}

app/templates/post.html
{% extends 'base.html' %}

{% block body %}
<ul class="posts">
  <li class="post">
    <a class="nostyle" href="{{ url_for('boards.post', boardname=post.board.name, postid=post.id) }}">
      <p class="msg">{{ post.content }}</p></a>
    
    <p class="author">
      <a href="{{ url_for('users.profile', username=post.user.username) }}" class="nounder">
	<img class="av-sm" alt="user profile picture" src="{{ url_for('static', filename='media/users/'+post.user.avatar) }}"/>
      </a>
      <a class="name" href="{{ url_for('users.profile', username=post.user.username) }}">{{ post.user.username }}</a>
      {{ post.date }}
    </p>
  </li>
</ul>

<h3>Reply</h3>
{% if current_user.is_authenticated %}
<form action="{{ url_for('boards.post', boardname=post.board.name, postid=post.id) }}" method="POST">
  {{ form.hidden_tag() }}

  {% for message in form.content.errors %}
    {{ message }}
  {% endfor %}
  {{ form.content.label }}:<br>
  {{ form.content }}<br><br>

  {{ form.submit }}
</form>
{% else %}
Login to post a reply
{% endif %}

<h3>Replies</h3>
<ul class="posts">
  {% for post in replies %}
  <li class="post">
    <p class="msg">{{ post.content }}</p>
    
    <p class="author">
      <a href="{{ url_for('users.profile', username=post.user.username) }}" class="nounder">
	<img class="av-sm" alt="user profile picture" src="{{ url_for('static', filename='media/users/'+post.user.avatar) }}"/>
      </a>
      <a class="name" href="{{ url_for('users.profile', username=post.user.username) }}">{{ post.user.username }}</a>
      {{ post.date }}
    </p>
  </li>
{% endfor %}
</ul>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block body %}
<h3>{{ user.username }}'s Profile</h3>
{% if user.avatar %}
<a href="{{ url_for('static', filename='media/users/'+user.avatar) }}">
  <img alt="profile picture" src="{{ url_for('static', filename='media/users/'+user.avatar) }}" class="av-big"/>
</a>
{% endif %}

<div class="details">
  <p><i>user joined {{ user.joined }}</i></p>
  <p>{% if user.bio %}{{ user.bio }}{% else %}<i>This user has no bio...</i>{% endif %}</p>
</div>

<div class="clear"></div>

{% if current_user == user %}
<h3>Edit Profile</h3>
<p>Only you can see this bit.</p>

<form action="{{ url_for('users.profile', username=user.username) }}" method="POST" enctype="multipart/form-data">
  {{ form.hidden_tag() }}

  {% for message in form.bio.errors %}
  {{ message }}
  {% endfor %}
  {{ form.bio.label }}:<br>
  {{ form.bio }}<br><br>

  {% for message in form.avatar.errors %}
  {{ message }}
  {% endfor %}
  {{ form.avatar.label }}:<br>
  {{ form.avatar }}<br><br>
  
  {{ form.submit }}
</form>
{% endif %}
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block body %}
<p>Register below. Note that as we do not store email addresses account recovery is out of the question, so it is important you pick a password you will remember.</p>

<form action="{{ url_for('users.register') }}" method="POST">
  {{ form.hidden_tag() }}

  {% for message in form.username.errors %}
  {{ message }}
  {% endfor %}
  {{ form.username.label }}:<br>
  {{ form.username }}<br>

  {% for message in form.password.errors %}
  {{ message }}
  {% endfor %}
  {{ form.password.label }}:<br>
  {{ form.password }}<br>

  {% for message in form.confirmpassword.errors %}
  {{ message }}
  {% endfor %}
  {{ form.confirmpassword.label }}:<br>
  {{ form.confirmpassword }}<br><br>

  {{ form.submit }}
</form>
{% endblock %}